# Generated by Django 5.2.6 on 2025-09-27 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.course')),
            ],
            options={
                'unique_together': {('course', 'module_name', 'topic_name')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.staff'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_contact', models.CharField(blank=True, max_length=20)),
                ('batch', models.BooleanField(choices=[(True, 'Morning'), (False, 'Afternoon')], default=True)),
                ('mode', models.BooleanField(choices=[(True, 'Offline'), (False, 'Online')], default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('sign', models.CharField(help_text='Staff full name', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.coursetopic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
